openapi: 3.0.1
info:
  title: Staple Invoice
  description: |+
    Scan the invoice document from file and explore the data by catagorywise. 
  version: '1.0'
  x-subscribelink: staple_invoice
servers:
  - url: 'https://dev-apis.sentient.io'
tags:
- name: "v1.0"
  description: "Published Date - Oct 30, 2020"
paths:
  /microservices/utility/stapleinvoice/v1/getresults:
    post:
      tags:
        - v1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  scanDocuments:
                    data:
                      BigBoxes:
                      - box:
                        - 904
                        - 118
                        - 1315
                        - 189
                        - 1109.5
                        - 153.5
                        - 'sentient.io'
                        - 'sentient.io'
                        page: 0
                      - box:
                        - 903
                        - 210
                        - 1312
                        - 229
                        - 1107.5
                        - 219.5
                        - |
                          NATURALLY
                          INTELLIGENT
                        - |
                          NATURALLY
                          INTELLIGENT
                        page: 0
                      - box:
                        - 186
                        - 346
                        - 366
                        - 386
                        - 276
                        - 366
                        - 'INVOICE
                
                '
                        - 'INVOICE
                
                '
                        page: 0
                      - box:
                        - 683
                        - 333
                        - 798
                        - 382
                        - 740.5
                        - 357.5
                        - |
                          Invoice Date
                          02 Oct 2020
                        - |
                          Invoice Date
                          02 Oct 2020
                        page: 0
                      - box:
                        - 1022
                        - 335
                        - 1207
                        - 466
                        - 1114.5
                        - 400.5
                        - |
                          Sentient_Mohamed
                          3 Fusionopolis Place
                          # 03-56 GALAXIS
                          WORK LOFT 138523
                          SINGAPORE
                        - |
                          Sentient_Mohamed
                          3 Fusionopolis Place
                          # 03-56 GALAXIS
                          WORK LOFT 138523
                          SINGAPORE
                        page: 0
                      - box:
                        - 683
                        - 419
                        - 841
                        - 466
                        - 762
                        - 442.5
                        - |
                          Account Number
                          495
                        - |
                          Account Number
                          495
                        page: 0
                      - box:
                        - 211
                        - 419
                        - 376
                        - 521
                        - 293.5
                        - 470
                        - |
                          Al org test
                          123 Thomson Rd
                          308123
                          SINGAPORE
                        - |
                          Al org test
                          123 Thomson Rd
                          308123
                          SINGAPORE
                        page: 0
                      - box:
                        - 683
                        - 502
                        - 830
                        - 548
                        - 756.5
                        - 525
                        - |
                          Invoice Number
                          INV-0019
                        - |
                          Invoice Number
                          INV-0019
                        page: 0
                      - box:
                        - 683
                        - 585
                        - 775
                        - 603
                        - 729
                        - 594
                        - 'Reference
                
                '
                        - 'Reference
                
                '
                        page: 0
                      - box:
                        - 170
                        - 731
                        - 286
                        - 757
                        - 228
                        - 744
                        - 'Description
                
                '
                        - 'Description
                
                '
                        page: 0
                      - box:
                        - 578
                        - 731
                        - 668
                        - 757
                        - 623
                        - 744
                        - 'Quantity
                
                '
                        - 'Quantity
                
                '
                        page: 0
                      - box:
                        - 711
                        - 731
                        - 810
                        - 752
                        - 760.5
                        - 741.5
                        - 'Unit Price
                
                '
                        - 'Unit Price
                
                '
                        page: 0
                      - box:
                        - 874
                        - 733
                        - 954
                        - 751
                        - 914
                        - 742
                        - 'Discount
                
                '
                        - 'Discount
                
                '
                        page: 0
                      - box:
                        - 1126
                        - 734
                        - 1160
                        - 752
                        - 1143
                        - 743
                        - 'Tax
                
                '
                        - 'Tax
                
                '
                        page: 0
                      - box:
                        - 1219
                        - 733
                        - 1347
                        - 752
                        - 1283
                        - 742.5
                        - 'Amount USD
                
                '
                        - 'Amount USD
                
                '
                        page: 0
                      - box:
                        - 167
                        - 794
                        - 397
                        - 814
                        - 282
                        - 804
                        - 'Top up of Sentient Credit
                
                '
                        - 'Top up of Sentient Credit
                
                '
                        page: 0
                      - box:
                        - 588
                        - 795
                        - 667
                        - 815
                        - 627.5
                        - 805
                        - '5,000.00
                
                '
                        - '5,000.00
                
                '
                        page: 0
                      - box:
                        - 773
                        - 794
                        - 809
                        - 814
                        - 791
                        - 804
                        - '0.01
                
                '
                        - '0.01
                
                '
                        page: 0
                      - box:
                        - 904
                        - 794
                        - 953
                        - 812
                        - 928.5
                        - 803
                        - '10.00
                
                '
                        - '10.00
                
                '
                        page: 0
                      - box:
                        - 1134
                        - 794
                        - 1160
                        - 812
                        - 1147
                        - 803
                        - '7%
                
                '
                        - '7%
                
                '
                        page: 0
                      - box:
                        - 1298
                        - 795
                        - 1348
                        - 813
                        - 1323
                        - 804
                        - '40.00
                
                '
                        - '40.00
                
                '
                        page: 0
                      - box:
                        - 825
                        - 836
                        - 1169
                        - 859
                        - 997
                        - 847.5
                        - 'Subtotal ( includes discount of $ 10.00 )
                
                '
                        - 'Subtotal ( includes discount of $ 10.00 )
                
                '
                        page: 0
                      - box:
                        - 1299
                        - 838
                        - 1348
                        - 856
                        - 1323.5
                        - 847
                        - '40.00
                
                '
                        - '40.00
                
                '
                        page: 0
                      - box:
                        - 770
                        - 877
                        - 1169
                        - 900
                        - 969.5
                        - 888.5
                        - 'Total Local supply of goods and services 7%
                
                '
                        - 'Total Local supply of goods and services 7%
                
                '
                        page: 0
                      - box:
                        - 1309
                        - 879
                        - 1348
                        - 896
                        - 1328.5
                        - 887.5
                        - '2.80
                
                '
                        - '2.80
                
                '
                        page: 0
                      - box:
                        - 1080
                        - 921
                        - 1169
                        - 940
                        - 1124.5
                        - 930.5
                        - 'Total USD
                
                '
                        - 'Total USD
                
                '
                        page: 0
                      - box:
                        - 1299
                        - 922
                        - 1348
                        - 939
                        - 1323.5
                        - 930.5
                        - '42.80
                
                '
                        - '42.80
                
                '
                        page: 0
                      - box:
                        - 989
                        - 960
                        - 1169
                        - 986
                        - 1079
                        - 973
                        - 'Total Net Payments
                
                '
                        - 'Total Net Payments
                
                '
                        page: 0
                      - box:
                        - 1309
                        - 963
                        - 1347
                        - 980
                        - 1328
                        - 971.5
                        - '0.00
                
                '
                        - '0.00
                
                '
                        page: 0
                      - box:
                        - 1006
                        - 1006
                        - 1169
                        - 1025
                        - 1087.5
                        - 1015.5
                        - 'Amount Due USD
                
                '
                        - 'Amount Due USD
                
                '
                        page: 0
                      - box:
                        - 1298
                        - 1006
                        - 1349
                        - 1025
                        - 1323.5
                        - 1015.5
                        - '42.80
                
                '
                        - '42.80
                
                '
                        page: 0
                      - box:
                        - 183
                        - 1103
                        - 504
                        - 1181
                        - 343.5
                        - 1142
                        - |
                          For GST reporting purposes
                          * Total Tax equivalent to SGD 3.82
                          1 SGD = 0.732767 USD
                        - |
                          For GST reporting purposes
                          * Total Tax equivalent to SGD 3.82
                          1 SGD = 0.732767 USD
                        page: 0
                      - box:
                        - 183
                        - 1311
                        - 1349
                        - 1371
                        - 766
                        - 1341
                        - |
                          Make all checks payable to SENTIENT.IO PTE LTD and mail to our address above Please write your invoice number
                          at the back of your check Alternatively you may perform a telegraphic transfer to our bank account below
                        - |
                          Make all checks payable to SENTIENT.IO PTE LTD and mail to our address above Please write your invoice number
                          at the back of your check Alternatively you may perform a telegraphic transfer to our bank account below
                        page: 0
                      - box:
                        - 181
                        - 1405
                        - 1317
                        - 1548
                        - 749
                        - 1476.5
                        - |
                          Bank DBS Limited
                          Swift code DBSSSGSG
                          Bank address 12 Marina Boulevard DBS Asia Central Marina Bay Financial Centre Tower 3 Singapore 018982
                          A/C Name SENTIENT.IO PTE LTD
                          A/C No.: 003-948675-8
                        - |
                          Bank DBS Limited
                          Swift code DBSSSGSG
                          Bank address 12 Marina Boulevard DBS Asia Central Marina Bay Financial Centre Tower 3 Singapore 018982
                          A/C Name SENTIENT.IO PTE LTD
                          A/C No.: 003-948675-8
                        page: 0
                      - box:
                        - 183
                        - 1623
                        - 415
                        - 1642
                        - 299
                        - 1632.5
                        - 'Due Date: 02 Oct 2020
                
                '
                        - 'Due Date: 02 Oct 2020
                
                '
                        page: 0
                      - box:
                        - 183
                        - 1950
                        - 829
                        - 1970
                        - 506
                        - 1960
                        - 'Registered Office 3 Fusionopolis Place # 03-56 GALAXIS WORK LOFT 138523
                          SINGAPORE
                
                '
                        - 'Registered Office 3 Fusionopolis Place # 03-56 GALAXIS WORK LOFT 138523
                          SINGAPORE
                
                '
                        page: 0
                      Currency:
                        UICategory: VAT & Amounts
                        UIName: Currency
                        UIType: Text
                        matches:
                        - keyword:
                          - 1080
                          - 921
                          - 1169
                          - 940
                          - 1124.5
                          - 930.5
                          - Total USD
                          - Total USD
                          match: USD
                          matchmulti: Total USD
                          page: 0
                          value:
                          - 1080
                          - 921
                          - 1169
                          - 940
                          - 1124.5
                          - 930.5
                          - Total USD
                          - Total USD
                        - keyword:
                          - 1006
                          - 1006
                          - 1169
                          - 1025
                          - 1087.5
                          - 1015.5
                          - Amount Due USD
                          - Amount Due USD
                          match: USD
                          matchmulti: Amount Due USD
                          page: 0
                          value:
                          - 1006
                          - 1006
                          - 1169
                          - 1025
                          - 1087.5
                          - 1015.5
                          - Amount Due USD
                          - Amount Due USD
                        - keyword:
                          - 183
                          - 1131
                          - 504
                          - 1155
                          - 343.5
                          - 1143
                          - "* Total Tax equivalent to SGD 3.82"
                          - "* Total Tax equivalent to SGD 3.82"
                          match: SGD
                          matchmulti: "* Total Tax equivalent to SGD 3.82"
                          page: 0
                          value:
                          - 183
                          - 1131
                          - 504
                          - 1155
                          - 343.5
                          - 1143
                          - "* Total Tax equivalent to SGD 3.82"
                          - "* Total Tax equivalent to SGD 3.82"
                      Customer: 
                      DetectedText: 'sentient.io NATURALLY INTELLIGENT INVOICE Invoice Date 02 Oct
                        2020 Sentient_Mohamed 3 Fusionopolis Place # 03-56 GALAXIS WORK LOFT 138523
                        SINGAPORE Account Number 495 Al org test 123 Thomson Rd 308123 SINGAPORE Invoice
                        Number INV-0019 Reference Description Quantity Unit Price Discount Tax Amount
                        USD Top up of Sentient Credit 5,000.00 0.01 10.00 7% 40.00 Subtotal ( includes
                        discount of $ 10.00 ) 40.00 Total Local supply of goods and services 7% 2.80
                        Total USD 42.80 Total Net Payments 0.00 Amount Due USD 42.80 For GST reporting
                        purposes * Total Tax equivalent to SGD 3.82 1 SGD = 0.732767 USD Make all
                        checks payable to SENTIENT.IO PTE LTD and mail to our address above Please
                        write your invoice number at the back of your check Alternatively you may
                        perform a telegraphic transfer to our bank account below Bank DBS Limited
                        Swift code DBSSSGSG Bank address 12 Marina Boulevard DBS Asia Central Marina
                        Bay Financial Centre Tower 3 Singapore 018982 A/C Name SENTIENT.IO PTE LTD
                        A/C No.: 003-948675-8 Due Date: 02 Oct 2020 Registered Office 3 Fusionopolis
                        Place # 03-56 GALAXIS WORK LOFT 138523 SINGAPORE '
                      DocSize:
                      - - 2000
                        - 1546
                      Email:
                        UICategory: Vendor & Customer
                        UIName: Email
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      GSTNumber:
                        UICategory: Vendor & Customer
                        UIName: GST Number
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      LineItems:
                      - - Amount:
                          - 40
                          Description:
                          - Top up of Sentient Credit
                          - '5,000.00'
                          - '0.01'
                          - '10.00'
                          - 7%
                        - Amount:
                          - 40
                          Description:
                          - Subtotal ( includes discount of $ 10.00 )
                        - Amount:
                          - 2.8
                          Description:
                          - Total Local supply of goods and services 7%
                      LineItems_standardHeader:
                      - - Description: Top up of Sentient Credit 5,000.00 0.01 10.00 7%
                          LineAmount: 40
                          Quantity: 1
                          UnitAmount: 40
                        - Description: Subtotal ( includes discount of $ 10.00 )
                          LineAmount: 40
                          Quantity: 1
                          UnitAmount: 40
                        - Description: Total Local supply of goods and services 7%
                          LineAmount: 2.8
                          Quantity: 1
                          UnitAmount: 2.8
                      OtherDate:
                        UICategory: Basic Information
                        UIName: Other Date
                        UIType: Date
                        matches:
                        - keyword: 
                          match: '2020-10-02'
                          matchmulti: 'Due Date: 02 Oct 2020'
                          page: 0
                          value:
                          - 183
                          - 1623
                          - 415
                          - 1642
                          - 299
                          - 1632
                          - 'Due Date: 02 Oct 2020'
                      SenderAddress:
                        UICategory: Vendor & Customer
                        UIName: Vendor Address
                        UIType: Text
                        matches:
                        - keyword:
                          - 904
                          - 118
                          - 1315
                          - 189
                          - 1109.5
                          - 153.5
                          - 'sentient.io
                
                '
                          - 'sentient.io
                
                '
                          match: |
                            Sentient_Mohamed
                            3 Fusionopolis Place
                            # 03-56 GALAXIS
                            WORK LOFT 138523
                            SINGAPORE
                          matchmulti: 'Sentient_Mohamed 3 Fusionopolis Place # 03-56 GALAXIS WORK
                            LOFT 138523 SINGAPORE'
                          page: 0
                          value:
                          - 1022
                          - 335
                          - 1207
                          - 466
                          - 1114.5
                          - 400.5
                          - |
                            Sentient_Mohamed
                            3 Fusionopolis Place
                            # 03-56 GALAXIS
                            WORK LOFT 138523
                            SINGAPORE
                          - |
                            Sentient_Mohamed
                            3 Fusionopolis Place
                            # 03-56 GALAXIS
                            WORK LOFT 138523
                            SINGAPORE
                      ServiceCharge:
                        UICategory: VAT & Amounts
                        UIName: Service Charge
                        UIType: Amount
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      SmallBoxes:
                      - box:
                        - 904
                        - 118
                        - 1315
                        - 189
                        - 1109.5
                        - 153.5
                        - sentient.io
                        - sentient.io
                        page: 0
                      - box:
                        - 903
                        - 210
                        - 1080
                        - 229
                        - 991.5
                        - 219.5
                        - NATURALLY
                        - NATURALLY
                        page: 0
                      - box:
                        - 1104
                        - 210
                        - 1312
                        - 229
                        - 1208
                        - 219.5
                        - INTELLIGENT
                        - INTELLIGENT
                        page: 0
                      - box:
                        - 186
                        - 346
                        - 366
                        - 386
                        - 276
                        - 366
                        - INVOICE
                        - INVOICE
                        page: 0
                      - box:
                        - 684
                        - 333
                        - 799
                        - 355
                        - 741.5
                        - 344
                        - Invoice Date
                        - Invoice Date
                        page: 0
                      - box:
                        - 683
                        - 363
                        - 793
                        - 382
                        - 738
                        - 372.5
                        - 02 Oct 2020
                        - 02 Oct 2020
                        page: 0
                      - box:
                        - 1023
                        - 335
                        - 1204
                        - 355
                        - 1113.5
                        - 345
                        - Sentient_Mohamed
                        - Sentient_Mohamed
                        page: 0
                      - box:
                        - 1023
                        - 362
                        - 1206
                        - 385
                        - 1114.5
                        - 373.5
                        - 3 Fusionopolis Place
                        - 3 Fusionopolis Place
                        page: 0
                      - box:
                        - 1024
                        - 393
                        - 1169
                        - 411
                        - 1096.5
                        - 402
                        - "# 03-56 GALAXIS"
                        - "# 03-56 GALAXIS"
                        page: 0
                      - box:
                        - 1023
                        - 419
                        - 1204
                        - 436
                        - 1113.5
                        - 427.5
                        - WORK LOFT 138523
                        - WORK LOFT 138523
                        page: 0
                      - box:
                        - 1024
                        - 447
                        - 1129
                        - 466
                        - 1076.5
                        - 456.5
                        - SINGAPORE
                        - SINGAPORE
                        page: 0
                      - box:
                        - 683
                        - 419
                        - 841
                        - 438
                        - 762
                        - 428.5
                        - Account Number
                        - Account Number
                        page: 0
                      - box:
                        - 683
                        - 447
                        - 715
                        - 466
                        - 699
                        - 456.5
                        - '495'
                        - '495'
                        page: 0
                      - box:
                        - 211
                        - 419
                        - 305
                        - 440
                        - 258
                        - 429.5
                        - Al org test
                        - Al org test
                        page: 0
                      - box:
                        - 214
                        - 445
                        - 364
                        - 468
                        - 289
                        - 456.5
                        - 123 Thomson Rd
                        - 123 Thomson Rd
                        page: 0
                      - box:
                        - 212
                        - 474
                        - 278
                        - 492
                        - 245
                        - 483
                        - '308123'
                        - '308123'
                        page: 0
                      - box:
                        - 213
                        - 502
                        - 318
                        - 521
                        - 265.5
                        - 511.5
                        - SINGAPORE
                        - SINGAPORE
                        page: 0
                      - box:
                        - 683
                        - 501
                        - 830
                        - 520
                        - 756.5
                        - 510.5
                        - Invoice Number
                        - Invoice Number
                        page: 0
                      - box:
                        - 685
                        - 530
                        - 767
                        - 548
                        - 726
                        - 539
                        - INV-0019
                        - INV-0019
                        page: 0
                      - box:
                        - 683
                        - 585
                        - 775
                        - 603
                        - 729
                        - 594
                        - Reference
                        - Reference
                        page: 0
                      - box:
                        - 170
                        - 731
                        - 286
                        - 757
                        - 228
                        - 744
                        - Description
                        - Description
                        page: 0
                      - box:
                        - 578
                        - 731
                        - 668
                        - 757
                        - 623
                        - 744
                        - Quantity
                        - Quantity
                        page: 0
                      - box:
                        - 711
                        - 732
                        - 810
                        - 753
                        - 760.5
                        - 742.5
                        - Unit Price
                        - Unit Price
                        page: 0
                      - box:
                        - 874
                        - 733
                        - 954
                        - 751
                        - 914
                        - 742
                        - Discount
                        - Discount
                        page: 0
                      - box:
                        - 1126
                        - 734
                        - 1160
                        - 752
                        - 1143
                        - 743
                        - Tax
                        - Tax
                        page: 0
                      - box:
                        - 1219
                        - 733
                        - 1347
                        - 752
                        - 1283
                        - 742.5
                        - AmountUSD
                        - Amount USD
                        page: 0
                      - box:
                        - 167
                        - 793
                        - 397
                        - 815
                        - 282
                        - 804
                        - Top up of Sentient Credit
                        - Top up of Sentient Credit
                        page: 0
                      - box:
                        - 588
                        - 795
                        - 667
                        - 815
                        - 627.5
                        - 805
                        - '5,000.00'
                        - '5,000.00'
                        page: 0
                      - box:
                        - 773
                        - 794
                        - 809
                        - 814
                        - 791
                        - 804
                        - '0.01'
                        - '0.01'
                        page: 0
                      - box:
                        - 904
                        - 794
                        - 953
                        - 812
                        - 928.5
                        - 803
                        - '10.00'
                        - '10.00'
                        page: 0
                      - box:
                        - 1134
                        - 794
                        - 1160
                        - 813
                        - 1147
                        - 803.5
                        - 7%
                        - 7%
                        page: 0
                      - box:
                        - 1298
                        - 795
                        - 1348
                        - 813
                        - 1323
                        - 804
                        - '40.00'
                        - '40.00'
                        page: 0
                      - box:
                        - 825
                        - 836
                        - 1169
                        - 859
                        - 997
                        - 847.5
                        - Subtotal ( includes discount of $ 10.00 )
                        - Subtotal ( includes discount of $ 10.00 )
                        page: 0
                      - box:
                        - 1299
                        - 838
                        - 1348
                        - 856
                        - 1323.5
                        - 847
                        - '40.00'
                        - '40.00'
                        page: 0
                      - box:
                        - 770
                        - 877
                        - 1169
                        - 900
                        - 969.5
                        - 888.5
                        - Total Local supply of goods and services 7%
                        - Total Local supply of goods and services 7%
                        page: 0
                      - box:
                        - 1309
                        - 879
                        - 1348
                        - 896
                        - 1328.5
                        - 887.5
                        - '2.80'
                        - '2.80'
                        page: 0
                      - box:
                        - 1080
                        - 921
                        - 1169
                        - 940
                        - 1124.5
                        - 930.5
                        - Total USD
                        - Total USD
                        page: 0
                      - box:
                        - 1299
                        - 922
                        - 1348
                        - 939
                        - 1323.5
                        - 930.5
                        - '42.80'
                        - '42.80'
                        page: 0
                      - box:
                        - 989
                        - 960
                        - 1169
                        - 986
                        - 1079
                        - 973
                        - Total Net Payments
                        - Total Net Payments
                        page: 0
                      - box:
                        - 1309
                        - 963
                        - 1347
                        - 980
                        - 1328
                        - 971.5
                        - '0.00'
                        - '0.00'
                        page: 0
                      - box:
                        - 1006
                        - 1006
                        - 1169
                        - 1025
                        - 1087.5
                        - 1015.5
                        - Amount Due USD
                        - Amount Due USD
                        page: 0
                      - box:
                        - 1298
                        - 1006
                        - 1349
                        - 1025
                        - 1323.5
                        - 1015.5
                        - '42.80'
                        - '42.80'
                        page: 0
                      - box:
                        - 183
                        - 1103
                        - 437
                        - 1128
                        - 310
                        - 1115.5
                        - For GST reporting purposes
                        - For GST reporting purposes
                        page: 0
                      - box:
                        - 183
                        - 1131
                        - 504
                        - 1155
                        - 343.5
                        - 1143
                        - "* Total Tax equivalent to SGD 3.82"
                        - "* Total Tax equivalent to SGD 3.82"
                        page: 0
                      - box:
                        - 184
                        - 1158
                        - 387
                        - 1177
                        - 285.5
                        - 1167.5
                        - 1 SGD = 0.732767 USD
                        - 1 SGD = 0.732767 USD
                        page: 0
                      - box:
                        - 184
                        - 1311
                        - 1349
                        - 1338
                        - 766.5
                        - 1324.5
                        - Make all checks payable to SENTIENT.IO PTE LTD and mail to our address above
                          Please write your invoice number
                        - Make all checks payable to SENTIENT.IO PTE LTD and mail to our address above
                          Please write your invoice number
                        page: 0
                      - box:
                        - 183
                        - 1343
                        - 1277
                        - 1371
                        - 730
                        - 1357
                        - at the back of your check Alternatively you may perform a telegraphic transfer
                          to our bank account below
                        - at the back of your check Alternatively you may perform a telegraphic transfer
                          to our bank account below
                        page: 0
                      - box:
                        - 183
                        - 1405
                        - 364
                        - 1426
                        - 273.5
                        - 1415.5
                        - Bank DBS Limited
                        - Bank DBS Limited
                        page: 0
                      - box:
                        - 183
                        - 1438
                        - 406
                        - 1459
                        - 294.5
                        - 1448.5
                        - Swift code DBSSSGSG
                        - Swift code DBSSSGSG
                        page: 0
                      - box:
                        - 184
                        - 1467
                        - 1310
                        - 1494
                        - 747
                        - 1480.5
                        - Bank address 12 Marina Boulevard DBS Asia Central Marina Bay Financial Centre
                          Tower 3 Singapore 018982
                        - Bank address 12 Marina Boulevard DBS Asia Central Marina Bay Financial Centre
                          Tower 3 Singapore 018982
                        page: 0
                      - box:
                        - 181
                        - 1497
                        - 513
                        - 1522
                        - 347
                        - 1509.5
                        - A/C Name SENTIENT.IO PTE LTD
                        - A/C Name SENTIENT.IO PTE LTD
                        page: 0
                      - box:
                        - 182
                        - 1528
                        - 415
                        - 1552
                        - 298.5
                        - 1540
                        - 'A/C No.: 003-948675-8'
                        - 'A/C No.: 003-948675-8'
                        page: 0
                      - box:
                        - 183
                        - 1623
                        - 415
                        - 1642
                        - 299
                        - 1632.5
                        - 'Due Date: 02 Oct 2020'
                        - 'Due Date: 02 Oct 2020'
                        page: 0
                      - box:
                        - 183
                        - 1950
                        - 829
                        - 1970
                        - 506
                        - 1960
                        - 'Registered Office 3 Fusionopolis Place # 03-56 GALAXIS WORK LOFT 138523
                          SINGAPORE'
                        - 'Registered Office 3 Fusionopolis Place # 03-56 GALAXIS WORK LOFT 138523
                          SINGAPORE'
                        page: 0
                      Subtotal:
                        UICategory: VAT & Amounts
                        UIName: Subtotal
                        UIType: Amount
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      Supplier: 
                      TableDetected: true
                      Tables:
                      - GridX:
                        - 167
                        - 1288
                        - 1358
                        GridY:
                        - 795
                        - 838
                        - 879
                        - 916
                        GridYPages:
                        - 0
                        - 0
                        - 0
                        - 0
                        HeaderPage: 0
                        header: []
                        headernum: 2
                      TaxTotal:
                        UICategory: VAT & Amounts
                        UIName: Tax Total
                        UIType: Amount
                        matches:
                        - keyword:
                          - 183
                          - 1131
                          - 504
                          - 1155
                          - 343.5
                          - 1143
                          - "* Total Tax equivalent to SGD 3.82"
                          - "* Total Tax equivalent to SGD 3.82"
                          match: 3.82
                          matchmulti: "* Total Tax equivalent to SGD 3.82"
                          page: 0
                          value:
                          - 183
                          - 1131
                          - 504
                          - 1155
                          - 343.5
                          - 1143
                          - "* Total Tax equivalent to SGD 3.82"
                          - "* Total Tax equivalent to SGD 3.82"
                      Total:
                        UICategory: VAT & Amounts
                        UIName: Total
                        UIType: Amount
                        matches:
                        - keyword:
                          - 1006
                          - 1006
                          - 1169
                          - 1025
                          - 1087.5
                          - 1015.5
                          - Amount Due USD
                          - Amount Due USD
                          match: 42.8
                          matchmulti: '42.80'
                          page: 0
                          value:
                          - 1298
                          - 1006
                          - 1349
                          - 1025
                          - 1323.5
                          - 1015.5
                          - '42.80'
                          - '42.80'
                      Type: receipt
                      UENNumber:
                        UICategory: Vendor & Customer
                        UIName: UEN Number
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      URL:
                        UICategory: Vendor & Customer
                        UIName: URL
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      num_pages: 1
                    docId: 7658
                    status: COMPLETED
                status: Success


        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/input'
        required: true              
components:
  schemas:
    success:
      type: object
      properties:
          results:
            type: object
            properties:          
              scanDocuments:
                type: object
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Oct 30, 2020
              description: Initial version release
    input:
      type: object
      required:
        - file
        - endpointUrl
      properties:
        file:
          type: string
          format: binary
          default: true
          example:  upload file
          description: The invoice document
        endpointUrl:
          type: string
          default: staple url
          description: The staple endpoint url          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
