openapi: 3.0.1
info:
  title: Staple Invoice
  description: |+
    Scan the Invoice document from file and explore the data by catagorywise. 
  version: '1.0'
  x-subscribelink: staple_receipt
servers:
  - url: 'https://dev-apis.sentient.io'
tags:
- name: "v1.0"
  description: "Published Date - Oct 30, 2020"
paths:
  /microservices/utility/stapleinvoice/v1/getresults:
    post:
      tags:
        - v1.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
		message: Successfully Processed
		results:
		  scanDocuments:
		    data:
		      BigBoxes:
		      - box:
			- 102
			- 131
			- 227
			- 166
			- 164.5
			- 148.5
			- 'GSSA'
			- 'GSSA'
			page: 0
		      Currency:
			UICategory: VAT & Amounts
			UIName: Currency
			UIType: Text
			matches:
			- keyword:
			  - 1160
			  - 1594
			  - 1171
			  - 1616
			  - 1165.5
			  - 1605
			  - "$"
			  - "$"
			  match: "$"
			  matchmulti: "$"
			  page: 0
			  value:
			  - 1160
			  - 1594
			  - 1171
			  - 1616
			  - 1165.5
			  - 1605
			  - "$"
			  - "$"
		      Customer: 
		      DetectedText: 'GSSA INVOICE Thank you c/o Greg Derderian Treasurer 32 Tinker
			Road Nashua NH 03064 Phone 603-595-4357 fax none DATE: INVOICE # FOR: May
			2 2009 100 Annual Dues Bill To: GSSA Member 2009 Phone DESCRIPTION AMOUNT
			Annual Dues per team 2009 summer swim season $ 100.00 TOTAL $ 100.00 Make
			all checks payable to GSSA If you have any questions concerning this invoice
			contact Na Greg Derderian Treasurer THANK YOU FOR YOUR MEMBERSHIP ! '
		      DocSize:
		      - - 2000
			- 1545
		      Email:
			UICategory: Vendor & Customer
			UIName: Email
			UIType: Text
			matches:
			- keyword: 
			  match: 
			  matchmulti: 
			  page: 
			  value: 
		      GSTNumber:
			UICategory: Vendor & Customer
			UIName: GST Number
			UIType: Text
			matches:
			- keyword: 
			  match: 
			  matchmulti: 
			  page: 
			  value: 
		      LineItems:
		      - - Amount:
			  - 22009
			  Description:
			  - 32 Tinker Road
			  - 'DATE:'
		      LineItems_standardHeader:
		      - - Description: '32 Tinker Road DATE:'
			  LineAmount: 22009
			  Quantity: 1
			  UnitAmount: 22009
			- Description: 'Nashua NH 03064 Phone 603-595-4357 fax none INVOICE # FOR:
			    Bill To: GSSA Member 2009 Phone DESCRIPTION'
			  LineAmount: 100
			  Quantity: 1
			  UnitAmount: 100
			- Description: Annual Dues per team 2009 summer swim season $
			  LineAmount: 100
			  Quantity: 1
			  UnitAmount: 100
		      OtherDate:
			UICategory: Basic Information
			UIName: Other Date
			UIType: Date
			matches:
			- keyword: 
			  match: '2009-05-02'
			  matchmulti: May 2 2009
			  page: 0
			  value:
			  - 1232
			  - 260
			  - 1367
			  - 289
			  - 1299
			  - 274
			  - May 2 2009
		      SenderAddress:
			UICategory: Vendor & Customer
			UIName: Vendor Address
			UIType: Text
			matches:
			- keyword:
			  - 102
			  - 131
			  - 227
			  - 166
			  - 164.5
			  - 148.5
			  - 'GSSA'
			  - 'GSSA'
			  match: |
			    c/o Greg Derderian Treasurer
			    32 Tinker Road
			    Nashua
			    NH 03064
			    Phone 603-595-4357
			    fax none
			  matchmulti: c/o Greg Derderian Treasurer 32 Tinker Road Nashua NH 03064
			    Phone 603-595-4357 Fax none
			  page: 0
			  value:
			  - 97
			  - 231
			  - 457
			  - 349
			  - 277
			  - 290
			  - |
			    c/o Greg Derderian Treasurer
			    32 Tinker Road
			    Nashua
			    NH 03064
			    Phone 603-595-4357
			    fax none
			  - |
			    c/o Greg Derderian Treasurer
			    32 Tinker Road
			    Nashua
			    NH 03064
			    Phone 603-595-4357
			    Fax none
		      ServiceCharge:
			UICategory: VAT & Amounts
			UIName: Service Charge
			UIType: Amount
			matches:
			- keyword: 
			  match: 
			  matchmulti: 
			  page: 
			  value: 
		      SmallBoxes:
		      - box:
			- 102
			- 131
			- 227
			- 166
			- 164.5
			- 148.5
			- GSSA
			- GSSA
			page: 0
		      Subtotal:
			UICategory: VAT & Amounts
			UIName: Subtotal
			UIType: Amount
			matches:
			- keyword: 
			  match: 
			  matchmulti: 
			  page: 
			  value: 
		      Supplier: 
		      TableDetected: true
		      Tables:
		      - GridX:
			- 91
			- 1222
			- 1377
			GridY:
			- 260
			- 292
			- 758
			- 778
			GridYPages:
			- 0
			- 0
			- 0
			- 0
			HeaderPage: 0
			header: []
			headernum: 2
		      TaxTotal:
			UICategory: VAT & Amounts
			UIName: Tax Total
			UIType: Amount
			matches:
			- keyword: 
			  match: 
			  matchmulti: 
			  page: 
			  value: 
		      Total:
			UICategory: VAT & Amounts
			UIName: Total
			UIType: Amount
			matches:
			- keyword:
			  - 1041
			  - 1591
			  - 1123
			  - 1616
			  - 1082
			  - 1603.5
			  - TOTAL
			  - TOTAL
			  match: 100
			  matchmulti: '100.00'
			  page: 0
			  value:
			  - 1286
			  - 1592
			  - 1359
			  - 1615
			  - 1322.5
			  - 1603.5
			  - '100.00'
			  - '100.00'
		      Type: receipt
		      UENNumber:
			UICategory: Vendor & Customer
			UIName: UEN Number
			UIType: Text
			matches:
			- keyword: 
			  match: 
			  matchmulti: 
			  page: 
			  value: 
		      URL:
			UICategory: Vendor & Customer
			UIName: URL
			UIType: Text
			matches:
			- keyword: 
			  match: 
			  matchmulti: 
			  page: 
			  value: 
		      num_pages: 1
		    docId: 7905
		    status: COMPLETED
		status: Success


        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/input'
        required: true              
components:
  schemas:
    success:
type: object
properties:
  results:
		scanDocuments:
		type: object
		properties:	  
			data:
				type: object
				properties:	 			
				  BigBoxes:
					type: array
					example: [{"box": [102,131,227,166,164.5,148.5],"page": 0}]
				  Currency:
					type: object
					properties:				  
						UICategory:
							type: string
							example: VAT & Amounts
						UIName: 
							type: string
							example: Currency
						UIType: 
							type: string
							example: Text						
						matches:
							type: array
							example: [1160,1594,1171]						
						  match: 
							type: string
							example: "$"							  
						  matchmulti:
							type: string
							example: "$"						  
						  page: 
							type: string
							example: 0							  
						  value:
							type: array
							example: [1160,1594,1171]
				  Customer:
				  		type: string
						example: null
				  DetectedText: 
				  		type: string
						example: GSSA INVOICE Thank you c/o Greg Derderian Treasurer 32 TinkerRoad Nashua NH 03064 Phone 603-595-4357 fax none DATE: INVOICE # FOR: May 2 2009 100 Annual Dues Bill To: GSSA Member 2009 Phone DESCRIPTION AMOUNT Annual Dues per team 2009 summer swim season $ 100.00 TOTAL $ 100.00 Make
				  DocSize:
					type: array
					example: [1160,1594,1171]
				  Email:
					UICategory:
						type: string
						example: Vendor & Customer
					UIName: 
						type: string
						example: Email
					UIType: 
						type: string
						example: Text					
					matches:
						type: array
						example: [{"keyword": null,"match": null}]				  
				  LineItems:
						type: object
						properties:				  
							Amount:
								type: string
								example: 22009
							Description:
								type: array
								example: [{"32 Tinker Road","DATE:"}]
				  num_pages: 
						type: string
						example: 1				  
			docId: 
				type: string
				example: 7905				
			status: 
				type: string
				example: COMPLETED			
  message:
	type: string
	example: Successfully Processed
	description: Detail description on the API status
  status:
	type: string
	example: Success
	description: The status of the API call success/failure 
              
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Oct 30, 2020
              description: Initial version release
    input:
      type: object
      required:
        - file
        - endpointUrl
      properties:
        file:
          type: string
          format: binary
          default: true
          example:  upload file
          description: The receipt document
        endpointUrl:
          type: string
          default: true
          description: The staple endpoint url          
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
